version: '3.7'

services:
  agent:
    image: paullj1/dyndns:latest
    environment:
      HOSTNAME: 'yourhost.com'
    secrets:
      - dyn_dns_user
      - dyn_dns_pass
    deploy:
      mode: replicated
      replicas: 1

secrets:
  dyn_dns_user:
    external: true
  dyn_dns_pass:
    external: true

